# It contains all the configs required in the project

DATA:
  SOURCE_URL: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"
  local_dir: data
  data_file_name: data.zip
  unzip_data_dir: data
  bad_data: bad_data
  parent_data_dir: PetImages