# It contains all the configs required in the project

DATA:
  SOURCE_URL: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"
  local_dir: data
  data_file_name: data.zip
  unzip_data_dir: data
  bad_data: bad_data
  parent_data_dir: PetImages
  model_dir: model
  initial_model_file: init_model.h5
  trained_model_file: trained_model.h5

params:
  learning_rate: 0.001
  loss: sparse_categorical_crossentropy
  metrics: ["accuracy"]
  img_shape: [180,180,3]
  batch_size: 32
  validation_split: 0.2
  buffer_size: 32
  epochs: 1
  seed: 42